import { defineType, defineField } from "sanity";
import { standardRichTextOf } from "../lib/schemaHelpers";

export const review = defineType({
  name: "review",
  title: "Review",
  type: "document",
  fields: [
    defineField({
      name: "name",
      title: "Restaurant Name",
      type: "string",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: { source: "name", maxLength: 96 },
      description: "Click Generate — this becomes the page URL (e.g. toko-bintang)",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "cardTeaser",
      title: "Card Teaser",
      type: "string",
      description: "One punchy line shown on the card below the location. Max 160 characters. Optional.",
      validation: (Rule) => Rule.max(160),
    }),
    defineField({
      name: "cuisine",
      title: "Cuisine Type",
      type: "string",
      description: "e.g. Japanese, Norwegian, Brunch, Fine Dining",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "area",
      title: "Area / Location",
      type: "string",
      description: "e.g. Stavanger Sentrum, Sandnes, Klepp",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "priceRange",
      title: "Price Range",
      type: "string",
      options: {
        list: [
          { title: "kr — Inexpensive", value: "kr" },
          { title: "kr kr — Moderate", value: "kr kr" },
          { title: "kr kr kr — Expensive", value: "kr kr kr" },
        ],
        layout: "radio",
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "bestFor",
      title: "Best For",
      type: "array",
      of: [{ type: "string" }],
      options: {
        list: [
          { title: "Date Night", value: "Date Night" },
          { title: "Lunch", value: "Lunch" },
          { title: "Groups", value: "Groups" },
          { title: "Solo", value: "Solo" },
          { title: "Family", value: "Family" },
          { title: "Business", value: "Business" },
          { title: "Late Night", value: "Late Night" },
          { title: "Outdoor Seating", value: "Outdoor Seating" },
        ],
        layout: "grid",
      },
    }),
    defineField({
      name: "websiteUrl",
      title: "Website URL",
      type: "url",
    }),
    defineField({
      name: "heroImage",
      title: "Hero Image",
      type: "image",
      options: { hotspot: true },
      fields: [
        defineField({
          name: "alt",
          title: "Alt Text",
          type: "string",
          description: "Describe the image for accessibility and SEO",
        }),
      ],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "tiktokUrl",
      title: "TikTok Video URL",
      type: "url",
      description: "Optional — paste the full TikTok video URL",
    }),
    defineField({
      name: "body",
      title: "Review Body",
      description: "Write your review. Use the photo block buttons to insert inline photos.",
      type: "array",
      of: standardRichTextOf,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "didItHitDifferent",
      title: "Worth the Calories? — Score",
      type: "number",
      description: "Food quality — Score 1–5",
      validation: (Rule) => Rule.required().min(1).max(5).integer(),
    }),
    defineField({
      name: "didItHitDifferentBlurb",
      title: "Worth the Calories? — Blurb",
      type: "text",
      rows: 2,
      description: "One or two sentences. What made it worth it (or not)?",
    }),
    defineField({
      name: "wouldIPayAgain",
      title: "Worth the Bill? — Score",
      type: "number",
      description: "Value for money — Score 1–5",
      validation: (Rule) => Rule.required().min(1).max(5).integer(),
    }),
    defineField({
      name: "wouldIPayAgainBlurb",
      title: "Worth the Bill? — Blurb",
      type: "text",
      rows: 2,
      description: "One or two sentences. Did the price feel fair?",
    }),
    defineField({
      name: "worthTheHype",
      title: "Worth the Hype? — Score",
      type: "number",
      description: "Does it live up to its reputation? — Score 1–5. Leave blank if not applicable.",
      validation: (Rule) => Rule.min(1).max(5).integer(),
    }),
    defineField({
      name: "worthTheHypeBlurb",
      title: "Worth the Hype? — Blurb",
      type: "text",
      rows: 2,
      description: "One or two sentences. Does the buzz match reality?",
    }),
    defineField({
      name: "theRealDeal",
      title: "Worth the Detour? — Score",
      type: "number",
      description: "Is it worth going out of your way for? — Score 1–5. Leave blank if not applicable.",
      validation: (Rule) => Rule.min(1).max(5).integer(),
    }),
    defineField({
      name: "theRealDealBlurb",
      title: "Worth the Detour? — Blurb",
      type: "text",
      rows: 2,
      description: "One or two sentences. Would you cross town for it?",
    }),
    defineField({
      name: "didStaffCare",
      title: "Worth Going Back For? — Score",
      type: "number",
      description: "Overall — would you return? — Score 1–5",
      validation: (Rule) => Rule.required().min(1).max(5).integer(),
    }),
    defineField({
      name: "didStaffCareBlurb",
      title: "Worth Going Back For? — Blurb",
      type: "text",
      rows: 2,
      description: "One or two sentences. What would bring you back?",
    }),
    defineField({
      name: "publishedAt",
      title: "Published Date",
      type: "datetime",
      initialValue: () => new Date().toISOString(),
    }),
    defineField({
      name: "featured",
      title: "Featured on Homepage",
      type: "boolean",
      initialValue: false,
    }),
  ],
  preview: {
    select: {
      title: "name",
      subtitle: "cuisine",
      media: "heroImage",
    },
  },
});
